# Generated by Django 6.0.1 on 2026-01-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exemplo', '0002_cliente_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(null=True),
        ),
    ]
