# Generated by Django 6.0.1 on 2026-01-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exemplo', '0003_cliente_data_nasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_barras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_validade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='fabricante',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
