# Generated by Django 6.0.1 on 2026-01-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exemplo', '0004_produto_cod_barras_produto_data_validade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cod_barras',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
    ]
