# Generated by Django 6.0.1 on 2026-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exemplo', '0005_remove_produto_cod_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='anotacao',
            field=models.TextField(null=True),
        ),
    ]
