# Generated by Django 6.0.1 on 2026-02-04 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('video', 'Video'), ('audio', 'Audio'), ('imagem', 'Imagem')], default='texto')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemaToConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_aprofundamento', models.PositiveIntegerField(default=1)),
                ('nivel_associacao', models.PositiveIntegerField(default=1)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astro.conteudo')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astro.tema')),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='temas_relacionados',
            field=models.ManyToManyField(through='astro.TemaToConteudo', to='astro.tema'),
        ),
    ]
