# Generated by Django 6.0.1 on 2026-02-04 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociacaoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_interconexao', models.PositiveIntegerField(default=1)),
                ('nivel_associacao', models.PositiveIntegerField(default=1)),
                ('tema1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tema1', to='astro.tema')),
                ('tema2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tema2', to='astro.tema')),
            ],
        ),
    ]
