# Generated by Django 6.0.1 on 2026-02-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0002_associacaotema'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='associacaotema',
            unique_together={('tema1', 'tema2')},
        ),
    ]
